verson: "3.7"

services:
  nginx:
    build:
      context: ./srcs/requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
    volumes:
      - ./wordpress_data:/var/www/html
    ports:
      - "443:443"
    networks:
      - intra
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    volumes:
      - ./wordpress_data:/var/www/html
    networks:
      - intra
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./srcs/requirements/mariadb
      dockerfile: ./Dockerfile
    volumes:
      - ./mariadb_data:/var/lib/mysql
    networks:
      - intra
    env_file:
      - .env
    restart: always

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/$USER/data/wordpress_data
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/$USER/data/mariadb_data

networks:
  intra:
    driver: bridge
