version: "3"

services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    depends_on:
      - wordpress
    volumes:
      - $HOME/data/wordpress_db:/var/www/html
    ports:
      - "443:443"
    networks:
      - intra
    env_file:
      - .env
    restart: always

  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: ./Dockerfile
    depends_on:
      - mariadb
    volumes:
      - $HOME/data/wordpress_db:/var/www/html
    networks:
      - intra
    env_file:
      - .env
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    networks:
      - intra
    volumes:
      - $HOME/data/mariadb_db:/var/lib/mysql
    env_file:
      - .env
    restart: always

# volumes:
#   wordpress_db:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: $HOME/data/wordpress
#   mariadb_db:
#     driver: local
#     driver_opts:
#       type: none
#       o: bind
#       device: $HOME/data/mariadb

networks:
  intra:
    driver: bridge
